name: Validate Badge Specs

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate badge specs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install check-jsonschema
        run: |
          python -m pip install --upgrade pip
          pip install check-jsonschema

      - name: Validate all badge specs
        run: |
          find specs -name '*.json' ! -name 'badge-schema.json' -print0 \
            | while IFS= read -r -d '' file; do
              echo "Validating $file"
              check-jsonschema "$file" --schemafile specs/v1.0.0/badge-schema.json
            done
